### ISSUE TITLE
Why do you need a loader at all?

### ISSUE THREAD

**Issue by danieliser** [tommcfarlin/WordPress-Plugin-Boilerplate#248]
First let me say I have developed several successful free and commercial plugins. I have also developed for many years with Kohana which is all OOP. So I understand most of the organizational structures and tools you have included.

However the hook & filter loader seems quite useless in several aspects.

First it requires more code to do the same job.

EX.
```php
$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_scripts' );
add_action( 'admin_enqueue_scripts', array( $plugin_admin, 'enqueue_scripts' ) );
```

That doesn't include the fact that the loader also has its own file & code on top of that statement there.

So that's roughly 130 lines of code vs 1 to do the same job.

Next comes the versatility of WP which must be maintained in my opinion as best as possible.

Although possible for me to correct myself with some extra work, your class currently contains no functionality to remove a hook or filter that has been en queued by the loader. This is not only due to the class not having any remove functions, but also due to the organization of the primary plugin class calling the admin scripts for example but not storing the initial class anywhere for reuse in a remove_action call.

For instance. Say I want to show a notice to anyone not using a paid extension that adds extra functions. (ex. Wanna use bg images in your theme, check out Advanced Theme). etc.

I would add it via a hook. And if they had Advanced Themes need to unhook it.

Without storing the original instance of the admin class used to make it, there is absolutely no way ( not including hacking `$_GLOBALS` ), to remove that hook.

As the loader functionality is built-in to WP already, I say don't bother with it. Its extra code to piggy back on a much simpler system.

Also your plugin class should call the admin controllers and store them at least inside the main class which should be either written in a Singleton Pattern, or by modifying your initial run function to store globally returning the same instance if it exists, creating and storing it if not.

Like so maybe.

```php
function plugin_name() {
    global $plugin_name;
    if(!$plugin_name) {
        $plugin_name = new Plugin_Name();
    }
    return $plugin_name;
}

function run_resolved() {
	plugin_name->run();
}
run_resolved();
```

Then if the admin controller were stored as a public variable in the `Plugin_Name` class i could remove actions using

```php
$class = plugin_name->admin_controller;
remove_action('my_custom_action', array($class,'function'));
```

Thanks for the huge efforts.

**Comment by tommcfarlin** [comment]
All of the points that you bring up are valid and are worth considering as a refactoring for the Loader, but first, let me back up and explain the *purpose* of the loader before I talk about it's implementation.

First, the Loader exists because far too many object-oriented plugins play double-duty with respect to working through their business logic *and* with registering themselves with WordPress. Ideally, there should be one class that's responsible for *just* dealing with actions and filters.

That is, a given class should strive to have a single reason to change. If a class is reponsible for maintaining its business logic *and* its hook logic, then it has more than one reason to change over time. I want to alleviate that.

To do this, I've created the Loader. The Loader allows us to register classes and hooks with WordPress through inversion of control and through dependency injection. This means that we can take the Loader, insert it into our classes (via constructors or setters) and then have the Loader accept the class and its callback methods for the hooks.

This gives our classes and our Loader a single reason to change (part of the [Single Responsibility Principle](http://en.wikipedia.org/wiki/Single_responsibility_principle)). 

Next, as far as 'remove' functionality is concerned, you're right. It doesn't include it - *yet*. It will; however, if you *really* need to remove functionality after you've hooked it up, you can still use the traditional `remove_filter` or `remove_action` to remove the hook.

This is something that will be added in a future version, but it's something that has to be done in priority order of other issues.

Thanks for all these comments - hope this helps. Feel free to re-open this issue if you want to have more discussion on this topic (as I know we're all on the same page as trying to make the best possible decisions).
