### ISSUE TITLE
How should styles and scripts be enqueued? 

### ISSUE THREAD

**Issue by jolaurin** [tommcfarlin/WordPress-Plugin-Boilerplate#255]
What would be the best way to enqueue styles and scripts contained in the plugin directory?

Example: I use the foundation framework, files are located in the CSS and JS directory of my plugin.

**Comment by tommcfarlin** [comment]
Take a look at [this file](https://github.com/tommcfarlin/WordPress-Plugin-Boilerplate/blob/master/plugin-name/trunk/includes/class-plugin-name.php). It shows how to do this :).

**Comment by jolaurin** [comment]
I'm not quite sure to understand how all this works.. I'm sorry..

**Comment by jolaurin** [comment]
if I copy the code I have in foundation.css to my plugin-name-admin.css it works but it kinda breaks the wordpress dashboard css...

**Comment by tommcfarlin** [comment]
It might be best if you wait until the documentation for the Boilerplate has been completed :). I'm in the process of creating several videos now after which I plan to begin creating a site focused exclusively on documentation.

You shouldn't need to copy anything from `foundation.css` into `plugin-name-admin.css`. Instead, you'd move `foundation.css` into the `public/css` directory and enqueue it from there - you don't want to enqueue Foundation in the Dashboard (which is why it shouldn't be in the admin directory).
